version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    volumes:
      - ../../:/app
    ports:
      - 3001:3000
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: 'nest'
      POSTGRES_PASSWORD: 'root'
    restart: always
  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    ports:
      - 8080:8080

volumes:
  pgdata:


