version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    volumes:
      - ../../:/app
    ports:
      - 3001:3000
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    ports:
      - 8080:8080

volumes:
  pgdata:


