version: '3.0'

services:
  chain:
    container_name: chain
    ports: 
      - "8545:8545"
    networks:
      - shared_network
    build:
      context: .
    volumes:
      - ../../:/app
    restart: always

networks:
  shared_network:
    external: true

